### PR TITLE
feat(create-stylable-app): lean template and clean-ups

### PR DESCRIPTION
**Pull request by tzachbon**
Our current templates include good examples of Stylable components and stylesheets usages, but we want a lovely clean template with just the infrastructure.
This is helpful for the upcoming [video](https://github.com/wix/stylable/issues/2195).

###  What is added
- [x] New template `ts-react-webpack-lean`.
- [x] Extract globals from the reset file to a dedicated file.
- [x] New CSS reset.
- [x] Remove `.eslintignore` and add the ignore paths to the `.eslintrc`.
- [x] Change the order of `reset` and `globals` import.
- [x] Update the current stylesheet to use `st-import`.
- [x] Change the `@stylable/runtime` to be a dev dependecy.

### CODE REVIEW

**Comment by AviVahl** [comment]
"organize files in dedicated directories" <-- this has no benefit in the example project. can't see why we'd want that.

also, do we want add the default `font-family` from the previous reset to new `globals.d.ts`. we want the font to look properly in the example app, and this is a saner default for us.

**Comment by tzachbon** [comment]
> "organize files in dedicated directories" <-- this has no benefit in the example project. can't see why we'd want that.
> 
> also, do we want add the default `font-family` from the previous reset to new `globals.d.ts`. we want the font to look properly in the example app, and this is a saner default for us.

The fact that all your files are in the src directory makes it look cluttered and difficult to distinguish between the purpose of the files, therefore it's harder to refactor.

It’s easy to see that the popular practice is to have at least one level of separation, and we aim to give an easier time to as many audiences as possible. ([Small article about this topic](https://reactjs.org/docs/faq-structure.html))

**Comment by AviVahl** [comment]
There are only two example components and the user can decide on whatever structure he chooses. I think it's a bit over engineered to provide own structure and doesn't follow the "less opionated" approach we wanted to take with this boilerplate.

**Review by barak007 — APPROVED** [review]
If I would nitpick here I would replace the stylable.svg
with this content: 
```svg
<svg width="85" height="96" xmlns="http://www.w3.org/2000/svg">
  <defs>
    <linearGradient x1="66.5482535%" y1="-4.69211158%" x2="80.2718164%" y2="111.186421%" id="a">
      <stop stop-color="#7AD852" offset="0%"/>
      <stop stop-color="#3AB38B" offset="53.5842857%"/>
      <stop stop-color="#00BFC9" offset="100%"/>
    </linearGradient>
    <linearGradient x1="78.0937359%" y1=".73760406%" x2="20.393625%" y2="118.621864%" id="b">
      <stop stop-color="#FF2953" offset="0%"/>
      <stop stop-color="#EA3333" offset="100%"/>
    </linearGradient>
  </defs>
  <g fill="none" fill-rule="evenodd">
    <path d="M25.9459514 1.83180599C18.0674566 5.18385626.06082708 22.4410604 0 36.0399542c.10608222 14.0584249 18.0674566 30.8565398 25.9459514 34.20859 1.8065142.768077 4.6097108 1.8313641 7.5703014 1.8313641 2.6998793 0 4.9859701-1.3323011 7.3121485-4.1301693 3.9097909-4.7034768 3.4393266-11.4664028-1.7713832-15.3045777-6.2355297-4.5903423-11.338845-8.7105432-11.4452399-16.6052071.1063949-7.8942221 5.2097102-13.4042761 11.4452399-17.9950603 5.2107098-3.837733 6.225538-9.65924406 2.3157471-14.36272081C39.0470265.88430489 36.2156924 0 33.5162528 0c-2.9610302 0-5.7637872 1.06328714-7.5703014 1.83180599Z" fill="url(#a)"/>
    <path d="M40.6969697 68.1290323c3.4580027-3.9332426 3.887312-11.7358889-1.5404165-15.483871-7.6080248-5.2535311-11.4916769-10.2618177-11.4461246-16.6799992.0516554-7.2780999 4.6833695-11.8354124 5.8377049-13.2554847-17.2757073 19.3954818-19.66858 41.3097495-2.9434847 49.0298251 3.8267556 1.330527 7.1044672-.2119903 10.0923209-3.6104702Z" fill="#005892"/>
    <path d="M32.6187986 61.1659305c2.2198441-2.7280651 2.008428-7.9002579-.9888612-10.739487-4.7659739-4.5146435-5.6169142-9.4261099-5.5876722-13.8777083.0331599-5.048031 3.006461-8.2089459 3.7474797-9.1938965-11.0900369 13.4525485-14.386226 30.9607029-3.6496513 36.3152846 2.4565629.9228427 4.5606702-.1470347 6.478705-2.5041928Z" fill="#00418E"/>
    <path d="M27.9147528 55.8977447c1.4165592-1.7408725 1.2816473-5.0414273-.6310264-6.8532374-3.0413325-2.8809498-3.5843469-6.015126-3.5656865-8.8558447.0211604-3.2213228 1.0424215-6.0017134-.6363028-2.2806399-1.6787243 3.7210734-6.1526484 16.1707905.6987305 19.5877339 1.5676175.5888977 2.910321-.093828 4.1342852-1.5980119Z" fill="#002355"/>
    <path d="M10.2201858 72.217956c-2.68661753 0-5.50450299-.8838128-7.81919462-3.6801241-3.89121979-4.7008596-2.87448283-10.5183396 2.31147657-14.3539371C10.9183792 49.5956651 15.9907251 44.0878855 16.0966146 36.1980561c-.1058895-7.890271-5.1846633-13.1303426-11.38414685-17.7418645C.1354802 15.0515727-1.49022861 8.55869822 2.40099118 3.8578387 4.71612037 1.06152735 7.53313071.17815621 10.2201858.17815621c2.946528 0 5.7364097 1.06269549 7.5343431 1.83034501C25.5956015 5.35868626 43.4366298 22.10568 43.5747924 36.1980561c-.0441854 13.2828065-17.9791909 30.8389282-25.8202635 34.1891132-1.7979334.7680912-4.5873775 1.8307867-7.5343431 1.8307867Z" fill="url(#b)" transform="translate(41.212121 23.741935)"/>
    <path d="M22.5574576 45.6907536c3.475639-3.9332425 2.886163-10.9922323-2.5692476-14.7402143-7.6468266-5.2535312-11.29253454-11.2768731-11.24674997-17.6950546C8.79337889 5.97738477 13.4487153 1.42007233 14.608938 0-3.43614578 13.2554847-5.15995421 41.3097495 11.6504411 49.0298251c3.8462726 1.3305269 7.9039244.0594085 10.9070165-3.3390715Z" fill="#470000" opacity=".60000002" style="mix-blend-mode:multiply" transform="rotate(-180 32.9696965 36.6451615)"/>
    <path d="M53.0031017 34.3179403c-2.2198441 2.728065-2.008428 7.9002579.9888612 10.739487 4.7659739 4.5146435 5.6169143 9.4261098 5.5876723 13.8777083-.0331599 5.048031-1.0431458 7.35170529-1.7841645 8.33665592 9.02623583-10.60832732 11.9766217-30.33502312 1.686336-35.45804402-2.4565629-.9228427-4.5606702.1470347-6.478705 2.5041928Z" fill="#670010"/>
    <path d="M23.8890459 33.9732608c1.4165591-1.7408725 1.2816472-5.0414273-.6310265-6.8532374-3.0413325-2.8809498-4.0595022-6.5378284-4.1735976-8.5652901-.1407262-2.5006865-.124156-2.8557106.3142424-4.6192494-1.3380859 2.4094053-7.1977211 19.0359527.3560964 21.6357888 1.5676176.5888978 2.9103211-.0938279 4.1342853-1.5980119Z" fill="#730000" style="mix-blend-mode:multiply" transform="rotate(-180 41.0101885 36.7295985)"/>
  </g>
</svg>

```

**Pull request merged**
